notes/notatki/urls.py
from django.urls import path
from notatki.views import MyLoginView, MyRegisterView, NotesList, NoteFormView, TagsListAndForm, \
    NoteDetailView, NoteUpdateView, HomeTemplateView

app_name = 'notatki'  #przestrzen nazw aplikacji
urlpatterns = [
    path("", HomeTemplateView.as_view(), name="home"),
    path('notatki/', NotesList.as_view(template_name='notatki/list.html'), name='notes_list'),
    path('notatki/<int:pk>', NoteDetailView.as_view(template_name='notatki/details.html'), name='details'),
    path('notatki/note_form', NoteFormView.as_view(template_name='notatki/noteform.html'), name='note_form'),
    path('notatki/note_form/<int:pk>', NoteUpdateView.as_view(template_name='notatki/noteform.html'), name='note_edit'),
    path('tags', TagsListAndForm.as_view(template_name='notatki/tags.html'), name='tags'),
    path('login', MyLoginView.as_view(template_name='notatki/login.html'), name='login'),
    path('register', MyRegisterView.as_view(template_name='notatki/register.html'), name='register'),
    path('logout', MyRegisterView.as_view(template_name='notatki/register.html'), name='logout'),
]

notes/notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notatki.urls'))
]

notes/notatki/models.py
from django.db import models

class UserProfile(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.user.username}'

class Note(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('UserProfile', on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return f'{self.title}'

class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)
    notes = models.ManyToManyField(Note, blank=True)
    def __str__(self):
        return f'{self.name}'

notes/notatki/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, CheckboxSelectMultiple
from notatki.models import Note, Tag
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Login')
    password = forms.CharField(label='Hasło', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_method = 'POST'

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_method = 'POST'

class NoteForm(ModelForm):

    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          widget=CheckboxSelectMultiple(),
                                          required=False
                                          )

    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']

    def __init__(self, instance, *args, **kwargs):
        if instance:    # pobieranie wcześniej wybranych tagów
            initial = {'tags': instance.tag_set.all()}
            kwargs['initial'] = initial
        super().__init__(instance=instance, *args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_method = 'POST'

class NoteSearchForm(forms.Form):
    search_title = forms.CharField(max_length=200, required=False)
    search_text = forms.CharField(max_length=200, required=False)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          widget=forms.CheckboxSelectMultiple,
                                          required=False
                                          )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('search', 'Szukaj'))
        self.helper.form_method = 'POST'

notes/notatki/views.py
from django.http import HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db import IntegrityError
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, FormView, DetailView
from django.contrib.auth import login, logout
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView

from notatki.forms import UserRegisterForm, UserLoginForm, NoteForm, NoteSearchForm
from notatki.models import UserProfile, Note, Tag

class NavBarHendler:
    def post(self, request, *args, **kwargs):
        if 'logout' in request.POST:
            logout(request)
            return redirect('notatki:home')
        if hasattr(super(), 'post'):
            return super().post(request, *args, **kwargs)
        return HttpResponse('Metoda post nie jest dostępna w klasie nadrzędnej.')


class HomeTemplateView(NavBarHendler, TemplateView):
    template_name = "notatki/home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        user = UserProfile.objects.get(user=self.request.user)
        context['dane'] = (Note.objects.filter(author=user).count)
        return context


@method_decorator(login_required, name='dispatch')
class NotesList(NavBarHendler, ListView, FormView):
    form_class = NoteSearchForm
    success_url = reverse_lazy('notatki:notes_list')
    def get_queryset(self):
        search_title = self.request.GET.get('search_title')
        search_text = self.request.GET.get('search_text')
        encoded_tags = self.request.GET.get('search_tags')

        profile = UserProfile.objects.get(user=self.request.user)
        queryset = Note.objects.filter(author=profile)
        if search_title:
            queryset = queryset.filter(title__icontains=search_title)
        if search_text:
            queryset = queryset.filter(content__icontains=search_text)
        if encoded_tags:
            search_tags = encoded_tags.split(',')
            queryset = queryset.filter(tag__in=search_tags)
        return queryset

    def post(self, request, *args, **kwargs):
        if 'delete_selected' in request.POST:
            selected_notes = request.POST.getlist('selected_notes')
            if selected_notes:
                # Usuń zaznaczone notatki
                Note.objects.filter(id__in=selected_notes).delete()
                return redirect('notatki:notes_list')
        elif 'search' in request.POST:
            search_title = request.POST.get('search_title')
            search_text = request.POST.get('search_text')
            search_tags = request.POST.getlist('tags')
            param =''
            if search_title:
                param += f'?search_title={search_title}'
            if search_text:
                if param:
                    param += f'&search_text={search_text}'
                else:
                    param += f'?search_text={search_text}'
            if search_tags:
                encoded_tags =','.join(search_tags)
                if param:
                    param += f'&search_tags={encoded_tags}'
                else:
                    param += f'?search_tags={encoded_tags}'
            return redirect(reverse('notatki:notes_list') + param)
        return super().post(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class NoteDetailView(NavBarHendler, DetailView):
    model = Note

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        note = self.get_object()
        tags = Tag.objects.filter(notes=note.id)
        context['tags'] = tags
        return context
    def post(self, request, *args, **kwargs):
        if 'delete_note' in request.POST:
            self.get_object().delete()
            return redirect(reverse('notatki:notes_list'))
        return super().post(request, *args, **kwargs)

class MyLoginView(LoginView):
    form_class = UserLoginForm
    next_page = 'notatki:notes_list'
    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class MyRegisterView(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('notatki:notes_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        # Tworzenie UserProfile po utworzeniu użytkownika
        UserProfile.objects.create(user=user)
        # Automatyczne logowanie użytkownika
        login(self.request, user)
        return response

@method_decorator(login_required, name='dispatch')
class NoteFormView(NavBarHendler, CreateView):

    form_class = NoteForm
    success_url = reverse_lazy('notatki:notes_list')
    def form_valid(self, form):
        instance = form.save(commit=False)
        profile = UserProfile.objects.get(user=self.request.user)
        instance.author = profile
        instance.save()
        # Pobierz wybrane tagi z formularza
        tags = form.cleaned_data['tags']

        # Dodaj notatkę do wybranych tagów
        for tag in tags:
            tag.notes.add(instance)

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class NoteUpdateView(NavBarHendler, UpdateView):
    queryset = Note.objects.all()
    form_class = NoteForm

    def get_success_url(self):
        return reverse('notatki:details', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        note = form.save(commit=False)
        note.save()

        # Pobierz wybrane tagi z formularza
        tags = form.cleaned_data['tags']

        # Dodaj notatkę do wybranych tagów
        note.tag_set.clear()
        for tag in tags:
            tag.notes.add(note)
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class TagsListAndForm(NavBarHendler, ListView):
    model = Tag

    def post(self, request, *args, **kwargs):
        if 'delete_selected' in request.POST:
            selected_tags = request.POST.getlist('selected_tags')
            if selected_tags:
                # Usuń zaznaczone tagi
                Tag.objects.filter(id__in=selected_tags).delete()
            return self.get(request, *args, **kwargs)
                # return reverse_lazy('notatki:tags')
        elif 'tag_name' in request.POST:
            try:
                tag_name = request.POST['tag_name']
                if tag_name:
                    Tag.objects.create(name=tag_name)
            except IntegrityError:
                # Jeśli wystąpił błąd IntegrityError, oznacza to, że tag o podanej nazwie już istnieje
                # Dodajemy komunikat do kolejki wiadomości
                messages.error(request, 'Tag o podanej nazwie już istnieje.')
            return self.get(request, *args, **kwargs)
        return super().post(request, *args, **kwargs)

notes/notatki/templates/notatki/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg mx-5 navbar-dark bg-dark rounded-4 ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'notatki:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notatki:notes_list' %}">Notatki</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notatki:note_form' %}">Nowa notatka</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notatki:tags' %}">Tagi</a>
        </li>

      </ul>
      {% if user.is_authenticated %}
        <form method="POST" class="d-flex" role="search">
          {% csrf_token %}
          <input  type="submit" class="btn btn-outline-success me-2" name="logout" value="Wyloguj">
        </form>
      {% else %}
        <form action="{% url 'notatki:login' %}" method="get">
          <button type="submit" class="btn btn-outline-success me-2">Login</button>
        </form>
        <form action="{% url 'notatki:register' %}" method="get">
          <button type="submit" class="btn btn-outline-success me-2">Register</button>
        </form>
      {% endif %}

    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

notes/notatki/templates/notatki/details.html
{% extends "notatki/base.html" %}
{% block title %} Szczegóły Notatki {% endblock %}
{% block content %}
<div class="container p-5 my-2 bg-dark text-white rounded-3 shadow-lg">
    <h2> Tytuł: {{ note.title }} </h2>
    <p> Autor: {{ note.author }} </p>
    <p> Utworzona: {{ note.created }} </p>
    <p> {{ note.content }} </p>

    <form method="post">
        {% csrf_token %}
        <a class="btn btn-primary" href='{% url "notatki:note_edit"  note.id %}'>Edytuj</a>
        <input class="btn btn-primary" type="submit" name='delete_note' value="Kasuj">
    </form>
    <h2>Tagi:</h2>

      {% for tag in tags %}
        <span class="badge  bg-info">{{ tag.name }}</span>
      {% endfor %}

</div>
{% endblock %}

notes/notatki/templates/notatki/home.html
{% extends "notatki/base.html" %}
{% load  crispy_forms_tags %}
{% block title %} Strona Główna {% endblock %}
{% block content %}
  <div class="container p-4">
    {% if user.is_authenticated %}
      <h3> Witaj {{ user.username }}! </h3>
      <h4> Masz {{ dane }} notatki. </h4>
    {% else %}
      <h3> Musisz się zalogować aby móc korzystać z notatnika i przegladać swoje notatki. </h3>
    {% endif %}
  </div>

{% endblock %}

notes/notatki/templates/notatki/list.html
{% extends "notatki/base.html" %}
{% load  crispy_forms_tags %}
{% block title %} Lista Notatek {% endblock %}
{% block content %}
<div class="container p-5 my-2 bg-dark text-white rounded-3 shadow-lg">
  <div class="row">
    <div class="col-md-3">
      {% crispy form %}
    </div>

    <div class="col-md-9  ">
      <form method="post">
        {% csrf_token %}
        <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th>Tytuł</th>
              <th class="w-25 float-end">Skasuj</th>
            </tr>
          </thead>
          <tbody>
          {% for note in object_list %}

              <tr>
                <td><a href="{% url 'notatki:details' note.id %}">{{ note.title }}  </a></td>
                <td><input class="float-end me-3" type="checkbox" name="selected_notes" value="{{ note.id }}"></td>
              </tr>

          {% endfor %}
           </tbody>
        </table>
        <input class="btn btn-primary float-end" type="submit" name="delete_selected" value="Skasuj zaznaczone notatki">
      </form>
    </div>

  </div>
</div>
{% endblock %}

notes/notatki/templates/notatki/login.html
{% extends "notatki/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Logowanie {% endblock %}

{% block content %}
<div class="w-100 d-flex flex-column align-items-center justify-content-center">
    {% crispy form %}
</div>
{% endblock %}

notes/notatki/templates/notatki/noteform.html
{% extends "notatki/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Tworzenie nowej notatki {% endblock %}

{% block content %}
<div class="container p-5 my-2 bg-dark text-white rounded-3 shadow-lg pt-4 w-50 d-flex flex-column"
    {% crispy form %}
</div>
{% endblock %}

notes/notatki/templates/notatki/register.html
{% extends "notatki/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Logowanie {% endblock %}

{% block content %}
<div class="w-100 d-flex flex-column align-items-center justify-content-center">

    {% crispy form %}
</div>
{% endblock %}

notes/notatki/templates/notatki/tags.html
{% extends "notatki/base.html" %}
{% load  crispy_forms_tags %}
{% block title %} Tagi {% endblock %}
{% block content %}
<div class="container p-5 my-2 bg-dark text-white rounded-3 shadow-lg pt-4">
  <form method="post">
  {% csrf_token %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-warning">
        <strong>{{ message }}</strong>
      </div>
    {% endfor %}
  {% endif %}

  <input type="text" name="tag_name" placeholder="Wprowadź nowy tag">
  <input type="submit" name="add_tag" value="Dodaj Tag">

  {% for tag in object_list %}
    <div class="container">
      <ul>
        <li>
          {{ tag.name }}
          <input type="checkbox" name="selected_tags" value="{{ tag.id }}">
        </li>
      </ul>
    </div>
  {% endfor %}

  <input type="submit" name="delete_selected" value="Skasuj zaznaczone notatki">


</form>
</div>
{% endblock %}